### ISSUE TITLE
Listen to changes in `data` attribute/property

### ISSUE THREAD

**Issue by LostInBrittany** [pankajpatel/inspector-component#3]
Right now, `inspector-component` gets the value of data attribute at construction time, and builds the tree. 

If the value is changed after construction (for example it it depends on a asynchronous operation), the new attribute value isn't read and the tree doesn't update. Same thing if changes happen the JS property `data`.

I am preparing a PR to fix that :)

**Comment by pankajpatel** [comment]
It will be a nice feature but feels like less needed because the component has the method to log more data in itself. So any update can easily be passed in a similar way as to console.log
